<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>cc0529e8-d6f2-4a28-aa33-1cbc27e91be4</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
        <PackageReference Include="WitcherKM.Common.Core" Version="0.1.5"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\shared\appsettings.json">
            <Link>appsettings.json</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Planner.Infrastructure\Planner.Infrastructure.csproj"/>
        <ProjectReference Include="..\Planner.Application\Planner.Application.csproj"/>
    </ItemGroup>

</Project>
