<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="WitcherKM.Common.Domain" Version="0.1.5" />
        <PackageReference Include="WitcherKM.Common.Core" Version="0.1.5" />
    </ItemGroup>

</Project>